### ISSUE TITLE
No need for a new Promise here, `fetch` already returns a Promise - so just do `return fetch...`

### ISSUE THREAD

**Issue by hyolyeng** [bj2jung/Yahoo-Fantasy-Basketball-Player-Comparison-Chrome-Extension#1]
https://github.com/bj2jung/Yahoo-Fantasy-Basketball-Player-Comparison-Chrome-Extension/blob/c28b8e0d537ca6aae359a690b7ac310399da49c2/content.js#L108

**Comment by bj2jung** [comment]
Done!

**Comment by hyolyeng** [comment]
Two more:

https://github.com/bj2jung/Yahoo-Fantasy-Basketball-Player-Comparison-Chrome-Extension/blob/e01bcbb4274400026374b9e04b110e2eb8a170e3/content.js#L575

https://github.com/bj2jung/Yahoo-Fantasy-Basketball-Player-Comparison-Chrome-Extension/blob/e01bcbb4274400026374b9e04b110e2eb8a170e3/content.js#L503

**Comment by bj2jung** [comment]
Done!
