### ISSUE TITLE
nit: can use single line if statement:

### ISSUE THREAD

**Issue by hyolyeng** [bj2jung/Yahoo-Fantasy-Basketball-Player-Comparison-Chrome-Extension#2]
https://github.com/bj2jung/Yahoo-Fantasy-Basketball-Player-Comparison-Chrome-Extension/blob/c28b8e0d537ca6aae359a690b7ac310399da49c2/content.js#L122

`if (playerOnMyRoster) myRoster[0].push(playerOnMyRoster.innerText)`

**Comment by bj2jung** [comment]
Done!
